title: Tahrovin Grit Wiki
description: A wiki for the Tahrovin Grit modlist
theme: just-the-docs
color_scheme: dark
logo: "/img/Tahrovin.png"


url: aeloverim.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
